import Navbar from "@/components/navbar";
import "./globals.css";
import Footer from "@/components/footer";

export const metadata = {
  title: "Barbie Movies",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col justify-between min-h-screen bg-pink-200 text-gray-800 gap-10">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
